"""Hardware-independent trial protocol utilities.

This module defines utilities to build randomized trial lists and to simulate
or manage the phase progression of an experimental acquisition protocol.

It intentionally does not depend on EEG, sEMG, IMU, GUI, LabVIEW, or cRIO code.
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Sequence, Tuple

from .event_markers import (
    PHASE_DURATIONS_SEC,
    PHASE_ORDER,
    START_PROTOCOL_MARKER,
    MANUAL_STOP_MARKER,
    get_block_movements,
    get_movement_display_name,
    get_phase_marker,
)


@dataclass(frozen=True)
class ProtocolEvent:
    """Event generated by the experimental protocol."""

    time_s: float
    marker: float
    label: str


@dataclass
class TrialProtocol:
    """Hardware-independent trial protocol state machine.

    Parameters
    ----------
    trial_list:
        Ordered list of movement codes for the session.
    phase_durations:
        Dictionary with phase durations in seconds.
    phase_order:
        Ordered sequence of phase names.
    session_start_time_s:
        Time origin used to express event timestamps.
    """

    trial_list: List[str]
    phase_durations: Dict[str, float] = field(
        default_factory=lambda: dict(PHASE_DURATIONS_SEC)
    )
    phase_order: Tuple[str, ...] = PHASE_ORDER
    session_start_time_s: float = 0.0

    current_trial_idx: int = 0
    current_phase_idx: int = 0
    protocol_started: bool = False
    is_finished: bool = False
    events: List[ProtocolEvent] = field(default_factory=list)

    def start(self, time_s: float = 0.0) -> ProtocolEvent:
        """Start the protocol and register the start marker."""
        self.protocol_started = True
        self.is_finished = False
        self.current_trial_idx = 0
        self.current_phase_idx = 0

        event = ProtocolEvent(
            time_s=time_s - self.session_start_time_s,
            marker=START_PROTOCOL_MARKER,
            label="InicioProtocolo",
        )
        self.events.append(event)
        return event

    def stop(self, time_s: float = 0.0, label: str = "FinManual") -> ProtocolEvent:
        """Stop the protocol manually and register the stop marker."""
        self.is_finished = True

        event = ProtocolEvent(
            time_s=time_s - self.session_start_time_s,
            marker=MANUAL_STOP_MARKER,
            label=label,
        )
        self.events.append(event)
        return event

    @property
    def current_phase(self) -> str:
        """Return the current phase name."""
        return self.phase_order[self.current_phase_idx]

    @property
    def current_movement(self) -> Optional[str]:
        """Return the current movement code, or None if the protocol is finished."""
        if self.is_finished or self.current_trial_idx >= len(self.trial_list):
            return None
        return self.trial_list[self.current_trial_idx]

    @property
    def num_trials(self) -> int:
        """Return the number of trials in the protocol."""
        return len(self.trial_list)

    def current_instruction_es(self) -> str:
        """Return the current instruction in Spanish."""
        movement = self.current_movement

        if not self.protocol_started:
            return "Pulsa ENTER para iniciar..."

        if self.is_finished or movement is None:
            return "Protocolo finalizado"

        movement_name = get_movement_display_name(movement)
        phase = self.current_phase

        if phase == "alert":
            return f"ALERTA\nPróximo: {movement_name}"
        if phase == "prep":
            return f"PREPARACIÓN\n{movement_name}"
        if phase == "execute":
            return f"EJECUCIÓN\n¡{movement_name} ahora!"
        if phase == "hold":
            return "SUJETA\nMantén la posición"
        if phase == "rest":
            return "DESCANSO\nRegresa a reposo"

        return "Fase desconocida"

    def advance_phase(self, time_s: float) -> Optional[ProtocolEvent]:
        """Advance the protocol to the next phase and register an event.

        Returns None if the protocol has not started or has already finished.
        """
        if not self.protocol_started or self.is_finished:
            return None

        movement = self.current_movement
        if movement is None:
            self.is_finished = True
            return None

        next_phase_idx = self.current_phase_idx + 1

        if next_phase_idx >= len(self.phase_order):
            self.current_trial_idx += 1
            next_phase_idx = 0

            if self.current_trial_idx >= len(self.trial_list):
                self.is_finished = True
                return None

            movement = self.current_movement

        self.current_phase_idx = next_phase_idx
        phase = self.current_phase

        event = ProtocolEvent(
            time_s=time_s - self.session_start_time_s,
            marker=get_phase_marker(phase),
            label=f"Fase={phase},Trial={self.current_trial_idx + 1},Mov={movement}",
        )
        self.events.append(event)
        return event

    def get_phase_duration(self, phase: Optional[str] = None) -> float:
        """Return the duration of a phase in seconds."""
        phase_name = phase or self.current_phase
        return self.phase_durations[phase_name]

    def as_event_rows(self) -> List[Tuple[float, float, str]]:
        """Return events as rows compatible with CSV writing."""
        return [(event.time_s, event.marker, event.label) for event in self.events]


def build_trial_list(
    movement_block: str,
    total_trials: int,
    seed: Optional[int] = None,
) -> List[str]:
    """Build a randomized and balanced trial list.

    Parameters
    ----------
    movement_block:
        Movement block name. Valid values are defined in MOVEMENT_BLOCKS.
    total_trials:
        Total number of trials. The value should be even for a balanced list.
    seed:
        Optional random seed for reproducible trial order.

    Returns
    -------
    list of str
        Randomized list of movement codes.
    """
    if total_trials <= 0:
        raise ValueError("total_trials must be greater than zero.")

    if total_trials % 2 != 0:
        raise ValueError("total_trials must be even to create a balanced protocol.")

    movement_a, movement_b = get_block_movements(movement_block)
    half = total_trials // 2

    trial_list = [movement_a] * half + [movement_b] * half

    rng = random.Random(seed)
    rng.shuffle(trial_list)

    return trial_list


def estimate_protocol_duration_sec(
    total_trials: int,
    phase_durations: Optional[Dict[str, float]] = None,
) -> float:
    """Estimate total protocol duration in seconds."""
    durations = phase_durations or PHASE_DURATIONS_SEC
    return float(total_trials * sum(durations.values()))


def validate_trial_list(trial_list: Sequence[str]) -> None:
    """Validate a trial list."""
    if not trial_list:
        raise ValueError("trial_list cannot be empty.")

    valid_codes = set()
    for block in ("Codo", "Hombro", "RotHombro"):
        valid_codes.update(get_block_movements(block))

    invalid = [movement for movement in trial_list if movement not in valid_codes]
    if invalid:
        raise ValueError(f"Invalid movement codes found: {invalid}")
